name: test Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: lint with pylint
      run: |
        make lint

  job1:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
            


